---
- include: network.yml param={{ item }}
  with_items: "{{ neutron.networks }}"

- include: subnet.yml param={{ item }}
  with_items: "{{ neutron.subnets }}"

- include: router.yml param={{ item }}
  with_items: "{{ neutron.routers }}"
